#ifndef PQCLEAN_SNTRUP761_CLEAN_CRYPTO_CORE_INVSNTRUP761_H
#define PQCLEAN_SNTRUP761_CLEAN_CRYPTO_CORE_INVSNTRUP761_H

#include <stdint.h>
#define PQCLEAN_SNTRUP761_CLEAN_crypto_core_invsntrup761_OUTPUTBYTES 1523
#define PQCLEAN_SNTRUP761_CLEAN_crypto_core_invsntrup761_INPUTBYTES 761
#define PQCLEAN_SNTRUP761_CLEAN_crypto_core_invsntrup761_KEYBYTES 0
#define PQCLEAN_SNTRUP761_CLEAN_crypto_core_invsntrup761_CONSTBYTES 0

int PQCLEAN_SNTRUP761_CLEAN_crypto_core_invsntrup761(unsigned char *outbytes, const unsigned char *inbytes);
#endif
