version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/scripts/copy_from_upstream"
      - "/.github/workflows"
    schedule:
      interval: "weekly"
    groups:
      pip:
        patterns:
          - "*"
