jobs:
  - name: Building and minimal testing on M1
    env:
      PYTEST_ARGS: tests/test_code_conventions.py tests/test_kat.py
    cmds:
      - uname -a && mkdir build && cd build && cmake -GNinja .. && ninja && cd .. && python3 -m pytest --verbose $PYTEST_ARGS

