jobs:
  - name: Building and minimal testing on M1
    env:
      PYTEST_ARGS: tests/test_code_conventions.py tests/test_kat.py
    cmds:
      - uname -a && mkdir build && cd build && cmake -GNinja .. && ninja && cd .. && python3 -m pytest --numprocesses=auto --verbose $PYTEST_ARGS ; rm -rf build
  - name: Building and testing using gcc-11 on M1
    cmds:
      - uname -a && mkdir build && cd build && cmake -DCMAKE_C_COMPILER=gcc-11 -GNinja .. && ninja && ninja run_tests ; cd .. && rm -rf build

