all:
	+ cd EncCPA ; make ;
	+ cd EncCCA ; make ;
	+ cd EncapCPA ; make ;
	+ cd EncapCCA ; make ;
	cp EncCPA/PQCencryptKAT_9217.rsp KAT-Test/lima_2p_1024_EncCPA-KAT.txt
	cp EncCPA/PQCencryptKAT_18433.rsp KAT-Test/lima_2p_2048_EncCPA-KAT.txt
	cp EncCPA/PQCencryptKAT_9163.rsp KAT-Test/lima_sp_1018_EncCPA-KAT.txt
	cp EncCPA/PQCencryptKAT_15673.rsp KAT-Test/lima_sp_1306_EncCPA-KAT.txt
	cp EncCPA/PQCencryptKAT_21865.rsp KAT-Test/lima_sp_1822_EncCPA-KAT.txt
	cp EncCPA/PQCencryptKAT_24745.rsp KAT-Test/lima_sp_2062_EncCPA-KAT.txt
	cp EncCCA/PQCencryptKAT_9217.rsp KAT-Test/lima_2p_1024_EncCCA-KAT.txt
	cp EncCCA/PQCencryptKAT_18433.rsp KAT-Test/lima_2p_2048_EncCCA-KAT.txt
	cp EncCCA/PQCencryptKAT_9163.rsp KAT-Test/lima_sp_1018_EncCCA-KAT.txt
	cp EncCCA/PQCencryptKAT_15673.rsp KAT-Test/lima_sp_1306_EncCCA-KAT.txt
	cp EncCCA/PQCencryptKAT_21865.rsp KAT-Test/lima_sp_1822_EncCCA-KAT.txt
	cp EncCCA/PQCencryptKAT_24745.rsp KAT-Test/lima_sp_2062_EncCCA-KAT.txt
	cp EncapCPA/PQCkemKAT_9217.rsp KAT-Test/lima_2p_1024_EncapCPA-KAT.txt
	cp EncapCPA/PQCkemKAT_18433.rsp KAT-Test/lima_2p_2048_EncapCPA-KAT.txt
	cp EncapCPA/PQCkemKAT_9163.rsp KAT-Test/lima_sp_1018_EncapCPA-KAT.txt
	cp EncapCPA/PQCkemKAT_15673.rsp KAT-Test/lima_sp_1306_EncapCPA-KAT.txt
	cp EncapCPA/PQCkemKAT_21865.rsp KAT-Test/lima_sp_1822_EncapCPA-KAT.txt
	cp EncapCPA/PQCkemKAT_24745.rsp KAT-Test/lima_sp_2062_EncapCPA-KAT.txt
	cp EncapCCA/PQCkemKAT_9217.rsp KAT-Test/lima_2p_1024_EncapCCA-KAT.txt
	cp EncapCCA/PQCkemKAT_18433.rsp KAT-Test/lima_2p_2048_EncapCCA-KAT.txt
	cp EncapCCA/PQCkemKAT_9163.rsp KAT-Test/lima_sp_1018_EncapCCA-KAT.txt
	cp EncapCCA/PQCkemKAT_15673.rsp KAT-Test/lima_sp_1306_EncapCCA-KAT.txt
	cp EncapCCA/PQCkemKAT_21865.rsp KAT-Test/lima_sp_1822_EncapCCA-KAT.txt
	cp EncapCCA/PQCkemKAT_24745.rsp KAT-Test/lima_sp_2062_EncapCCA-KAT.txt

clean:
	+ cd EncCPA ; make clean ;
	+ cd EncCCA ; make clean ;
	+ cd EncapCPA ; make clean ;
	+ cd EncapCCA ; make clean ;

