#ifndef PQCLEAN_MCELIECE348864_CLEAN_NAMESPACE_H
#define PQCLEAN_MCELIECE348864_CLEAN_NAMESPACE_H

#define CRYPTO_NAMESPACE(fun) PQCLEAN_MCELIECE348864_CLEAN_ ## fun
#define _CRYPTO_NAMESPACE(fun) _PQCLEAN_MCELIECE348864_CLEAN_ ## fun

#endif
