// auto generated by genmat.py
#ifndef EMI_TRANSFORM_H
#define EMI_TRANSFORM_H

#include "qruov.h"

#if QRUOV_q == 31 && QRUOV_L == 3
#define QRUOV_LL 5
#elif QRUOV_q == 127 && QRUOV_L == 3
#define QRUOV_LL 5
#elif QRUOV_q == 31 && QRUOV_L == 10
#define QRUOV_LL 19
#elif QRUOV_q == 7 && QRUOV_L == 10
#define QRUOV_LL 23
#elif QRUOV_q == 127 && QRUOV_L == 10
#define QRUOV_LL 19
#else
#error "Unsupported (q, L) for EMI tables"
#endif

void evaluate(uint8_t *output, int plane_out, const uint8_t *input, int plane_in, int size);
void reevaluate(uint8_t *output, int plane_out, const uint8_t *input, int plane_in, int size);
void interpolate(uint8_t *output, int plane_out, const uint8_t *input, int plane_in, int size);

#endif // EMI_TRANSFORM_H
