version: 2

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH} 
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Clone liboqs
        command: (cd oqs_test && scripts/clone_liboqs.sh) # unconditional checkout to test for changes there
    - run:
        name: Build liboqs
        command: .circleci/git_no_checkin_in_last_day.sh || (cd oqs_test && scripts/build_liboqs.sh)
    - run:
        name: Build OpenSSL
        command: .circleci/git_no_checkin_in_last_day.sh || (cd oqs_test && scripts/build_openssl.sh)
    - run:
        name: Run unit tests
        command: mkdir -p oqs_test/test-results && .circleci/git_no_checkin_in_last_day.sh || (LD_LIBRARY_PATH="$(pwd):$(pwd)/oqs/lib" make test && cd oqs_test && LD_LIBRARY_PATH="$(dirname $PWD);$(dirname $PWD)/oqs/lib" python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml)
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs_test/test-results

.macopenssl_job: &macopenssljob
    macos:
       xcode: "11.3.0"
    steps:
        - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
        - run:
            name: Install dependencies
            command: |
              .circleci/git_no_checkin_in_last_day.sh || (
              brew update &&
              brew unlink python@2 &&
              brew install cmake ninja doxygen astyle &&
              pip3 install --user pytest pytest-xdist nose rednose
              )
        - run:
            name: Clone liboqs
            command: (cd oqs_test && scripts/clone_liboqs.sh) # unconditional checkout
        - run:
            name: Build liboqs
            command: .circleci/git_no_checkin_in_last_day.sh || (cd oqs_test && scripts/build_liboqs.sh)
        - run:
            name: Build OpenSSL
            command: .circleci/git_no_checkin_in_last_day.sh || (cd oqs_test && scripts/build_openssl.sh)
        - run:
            name: Run unit tests
            command: mkdir -p oqs_test/test-results && .circleci/git_no_checkin_in_last_day.sh || (cd oqs_test && OQS_LIBPATH="$(dirname $PWD):$(dirname $PWD)/oqs/lib" python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml)
        - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
            path: oqs_test/test-results

jobs:
  debian-buster-amd64:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
  ubuntu-bionic-x86_64:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
  ubuntu-bionic-x86_64-noconn:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      SKIP_TESTS: connection
  ubuntu-bionic-x86_64-shared:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      LIBTYPE: shared
  ubuntu-bionic-x86_64-shared-noconn:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      LIBTYPE: shared
      SKIP_TESTS: connection
  macOS-shared-noconn:
    <<: *macopenssljob
    environment:
      LIBTYPE: shared
      SKIP_TESTS: connection
  macOS-shared:
    <<: *macopenssljob
    environment:
      LIBTYPE: shared
  macOS-static:
    <<: *macopenssljob
    environment:
      LIBTYPE: no-shared
      SKIP_TESTS: connection

workflows:
  version: 2
  build:
    jobs:
      - macOS-shared-noconn    
      - ubuntu-bionic-x86_64-shared
      - ubuntu-bionic-x86_64-noconn
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - OQS-OpenSSL_1_1_1-stable
    jobs:
      - macOS-shared    
      - debian-buster-amd64
      - macOS-static    
      - ubuntu-bionic-x86_64-shared-noconn
      - ubuntu-bionic-x86_64

