set(SOURCE_FILES_ID2ISO_GENERIC_REF
    ${LVLX_DIR}/id2iso.c
    ${LVLX_DIR}/dim2id2iso.c
)

add_library(${LIB_ID2ISO_${SVARIANT_UPPER}} STATIC ${SOURCE_FILES_ID2ISO_GENERIC_REF})
target_link_libraries(${LIB_ID2ISO_${SVARIANT_UPPER}} ${LIB_QUATERNION} ${LIB_PRECOMP_${SVARIANT_UPPER}} ${LIB_MP} ${LIB_GF_${SVARIANT_UPPER}} ${LIB_EC_${SVARIANT_UPPER}} ${LIB_HD_${SVARIANT_UPPER}})
target_include_directories(${LIB_ID2ISO_${SVARIANT_UPPER}} PRIVATE ${INC_PUBLIC} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_QUATERNION} ${INC_MP} ${INC_GF} ${INC_GF_${SVARIANT_UPPER}} ${INC_EC} ${INC_HD} ${INC_ID2ISO} ${INC_COMMON})
target_compile_options(${LIB_ID2ISO_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})
target_compile_definitions(${LIB_ID2ISO_${SVARIANT_UPPER}} PUBLIC SQISIGN_VARIANT=${SVARIANT_LOWER})

add_subdirectory(test)
