#ifndef ENCODED_SIZES_H
#define ENCODED_SIZES_H
#include <tutil.h>
#define SECURITY_BITS 256
#define CHALLENGE_BITS 256
#define RESPONSE_BITS 400
#define RESPONSE_BYTES 51
#define HASH_ITERATIONS 1
#define FP_ENCODED_BYTES 84
#define FP2_ENCODED_BYTES 168
#define CHALLENGE_BYTES 32
#define EC_CURVE_ENCODED_BYTES 168
#define EC_POINT_ENCODED_BYTES 168
#define EC_BASIS_ENCODED_BYTES 504
#define PUBLICKEY_BYTES 169
#define SECRETKEY_BYTES 549
#define SIGNATURE_BYTES 406
#if 0
#elif RADIX == 16
#define IBZ_NLIMBS 220
#elif RADIX == 32
#define IBZ_NLIMBS 110
#elif RADIX == 64
#define IBZ_NLIMBS 55
#endif
#endif
