name: SPHINCS+
type: signature
claimed-nist-level: 3
length-public-key: 48
length-secret-key: 96
length-signature: 17064
testvectors-sha256: 7e50b92ec85e31260326092a62e84d2f12df84213a494d0f0527125a5e6b7ed7
principal-submitter: Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
implementations:
    - name: clean
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
