// SPDX-License-Identifier: MIT
// This file was generated by {{ generated_by }}

#include <stdlib.h>

#include <oqs/kem_{{ kem_key }}.h>

#if defined(OQS_ENABLE_KEM_{{ param_key }})
OQS_KEM *OQS_KEM_{{ param_key }}_new(void) {

	OQS_KEM *kem = OQS_MEM_malloc(sizeof(OQS_KEM));
	if (kem == NULL) {
		return NULL;
	}
	kem->method_name = OQS_KEM_alg_{{ param_key }};
	kem->alg_version = "{{ version }}";

	kem->claimed_nist_level = {{ nist_level }};
	kem->ind_cca = {{ ind_cca | lower }};

	kem->length_public_key = OQS_KEM_{{ param_key }}_length_public_key;
	kem->length_secret_key = OQS_KEM_{{ param_key }}_length_secret_key;
	kem->length_ciphertext = OQS_KEM_{{ param_key }}_length_ciphertext;
	kem->length_shared_secret = OQS_KEM_{{ param_key }}_length_shared_secret;
	kem->length_keypair_seed = OQS_KEM_{{ param_key }}_length_keypair_seed;
	kem->length_encaps_seed = OQS_KEM_{{ param_key }}_length_encaps_seed;

	kem->keypair = OQS_KEM_{{ param_key }}_keypair;
	kem->keypair_derand = OQS_KEM_{{ param_key }}_keypair_derand;
	kem->encaps = OQS_KEM_{{ param_key }}_encaps;
	kem->encaps_derand = OQS_KEM_{{ param_key }}_encaps_derand;
	kem->decaps = OQS_KEM_{{ param_key }}_decaps;

	return kem;
}

extern int {{ default_impl["keypair"] }}(uint8_t *pk, uint8_t *sk);
{%- if default_impl["keypair_derand"] %}
extern int {{ default_impl["keypair_derand"] }}(uint8_t *pk, uint8_t *sk, const uint8_t *seed);
{%- endif %}
extern int {{ default_impl["enc"] }}(uint8_t *ct, uint8_t *ss, const uint8_t *pk);
{%- if default_impl["enc_derand"] %}
extern int {{ default_impl["enc_derand"] }}(uint8_t *ct, uint8_t *ss, const uint8_t *pk, const uint8_t *seed);
{%- endif %}
extern int {{ default_impl["dec"]  }}(uint8_t *ss, const uint8_t *ct, const uint8_t *sk);
#endif /* OQS_ENABLE_KEM_{{ param_key }} */
