#!/bin/bash

#Unarchive the library in their own directory 

cd  archive_temp
for c in `find . -name "*.a"`;do
  mkdir ${c}_1
  cp $c ${c}_1
  cd ${c}_1 
  ar x $c
  cd ..
done

#Find duplicate symbols 

find_dup() {
  symbs=$1
  array=()
  oldsymb='' 
  for symb in $symbs;do
    newsymb=$symb
    if [ ! -z "$oldsymb" ];then
      if [ "$newsymb" = "$oldsymb" ];then
        array+=' '
        array+=$oldsymb
      fi
    fi
    oldsymb=$newsymb
  done
  echo ${array[@]}
}

#Find all the object files (by name) which occur more than once 
#across all the algorithms and their implementations

objs=`find . -name "*.o" | awk  'BEGIN { FS = "/" } ; {print $3}'| sort`
dupes=`find_dup "$objs" | tr ' ' '\n' | uniq`

#Find unique object files by content (among files with duplicate names)
#across all the algorithms and their implementations

var=0
map=()
oldstr=
dif=0
same=0
for dupe in $dupes;do
  str=
  oldstr=
  newobjs=`find . -name "$dupe"|sort`
  for newstr in $newobjs;do 
    if [ ! -z "$oldstr" ];then
      m1=`md5sum $newstr| awk '{print $1}'`
      m2=`md5sum $oldstr | awk '{print $1}'`
      if [ "$m1" != "$m2" ];then
        if [ $dif -eq 0 ];then
          if [ $same -eq 0 ];then
            str+=$oldstr
          else
            same=0
            str+=' ' 
            str+=$oldstr
          fi
          dif=1 
        else
          str+=';' 
            str+=$oldstr
        fi 
      else
        if [ $same -eq 0 ];then
          if [ $dif -eq 0 ];then
            str+=$oldstr
          else
            dif=0
            str+=';' 
            str+=$oldstr
          fi
          same=1
        else
            str+=' ' 
            str+=$oldstr
        fi
      fi
    fi
    oldstr=$newstr
  done
    if [ $dif -eq 1 ];then
    dif=0
    str+=';' 
    str+=$newstr
  fi
  if [ $same -eq 1 ];then
    same=0
    str+=' ' 
    str+=$newstr
  fi

  case "$str" in 
  *\;*)
    map+=("$var"="$str")
    var=$((var+1))
    ;;
    *)
    ;;
  esac
done


:<<'END'
Make file names, text and data symbols unique.  
END

len=${#map[@]}
k=0
while [  $k -lt $len ]; do
  str=`echo ${map[$k]} | awk -F '=' '{print $2}'`
  IFS=';'; for word in $str; do 
    IFS=' ';for w in $word;do
    unique=$(echo $w | sed 's/\(.*\)\(.o\)/\1_'${var}'OQS\2/')
      mv $w $unique
      libdir=$(echo $unique | sed 's#./\(.*\)/.*#\1#')
      tsymbols=$(nm $unique | grep " T "| awk '{print $3}')
      unset IFS
      for tsymbol in $tsymbols;do
        case "$tsymbol" in 
          *OQS*)
            continue
          ;;
        esac
        objs=`find $libdir -name "*.o"`
        for obj in $objs;do
          if [ ! -z "$tsymbol" ];then
            objcopy --redefine-sym $tsymbol=${tsymbol}_$var $obj
          fi
        done
      done

      tsymbols=$(nm $unique | grep " D "| awk '{print $3}')
      for tsymbol in $tsymbols;do
        case "$tsymbol" in 
          *OQS*)
            continue
          ;;
        esac
        objs=`find $libdir -name "*.o"`
        for obj in $objs;do
          if [ ! -z "$tsymbol" ];then
            objcopy --redefine-sym $tsymbol=${tsymbol}_$var $obj
          fi
        done
      done
    done
    var=$((var+1))
  done
   k=$((k+1)) 
done

unset IFS
mkdir final_temp
ob=$(find . -name "*.o")
for obj in $ob;do
  cp $obj final_temp
done

cd final_temp
ar cr liboqs.a *.o 
cp liboqs.a ../..
cd ../..
