try_run(RUN_RESULT COMPILE_RESULT
        "${CMAKE_BINARY_DIR}" "${PROJECT_SOURCE_DIR}/.CMake/list_cpu_extensions.c"
        CMAKE_FLAGS
            -DINCLUDE_DIRECTORIES=${CPUFEATURES_INCLUDE_DIR}
        LINK_LIBRARIES CPUFEATURES
        RUN_OUTPUT_VARIABLE RUN_OUTPUT)
foreach(CPU_EXTENSION ${RUN_OUTPUT})
    set(OQS_USE_${CPU_EXTENSION}_INSTRUCTIONS TRUE)
endforeach()
if(OQS_USE_AVX512BW_INSTRUCTIONS AND
    OQS_USE_AVX512DQ_INSTRUCTIONS AND
    OQS_USE_AVX512F_INSTRUCTIONS)
    set(OQS_USE_AVX512_INSTRUCTIONS ON)
endif()
