# SPDX-License-Identifier: MIT

set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_CROSSCOMPILING OFF)

set(CMAKE_GENERATOR_PLATFORM
    x64
    CACHE STRING "Platform" FORCE
)
