# SPDX-License-Identifier: MIT

set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_CROSSCOMPILING ON)

set(CMAKE_GENERATOR_PLATFORM
    ARM64
    CACHE STRING "Platform" FORCE
)
