# SPDX-License-Identifier: MIT

set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_CROSSCOMPILING OFF)

set(CMAKE_GENERATOR_PLATFORM
    Win32
    CACHE STRING "Platform" FORCE
)
