#ifndef ENCODED_SIZES_H
#define ENCODED_SIZES_H
#include <tutil.h>
#define SECURITY_BITS 192
#define CHALLENGE_BITS 192
#define RESPONSE_BITS 302
#define RESPONSE_BYTES 38
#define HASH_ITERATIONS 1
#define FP_ENCODED_BYTES 64
#define FP2_ENCODED_BYTES 128
#define CHALLENGE_BYTES 24
#define EC_CURVE_ENCODED_BYTES 128
#define EC_POINT_ENCODED_BYTES 128
#define EC_BASIS_ENCODED_BYTES 384
#define PUBLICKEY_BYTES 129
#define SECRETKEY_BYTES 417
#define SIGNATURE_BYTES 306
#if 0
#elif RADIX == 16
#define IBZ_NLIMBS 160
#elif RADIX == 32
#define IBZ_NLIMBS 80
#elif RADIX == 64
#define IBZ_NLIMBS 40
#endif
#endif
