// rename exported sha3 functions for OQS global namespace

#ifndef OQS_NAMESPACE_PICNIC_H
#define OQS_NAMESPACE_PICNIC_H

#define BitLength oqs_sig_picnic_BitLength
#define BitSequence oqs_sig_picnic_BitSequence
#define HashReturn oqs_sig_picnic_HashReturn
#define KeccakF1600_FastLoop_Absorb oqs_sig_picnic_KeccakF1600_FastLoop_Absorb
#define KeccakP1600_AddBytes oqs_sig_picnic_KeccakP1600_AddBytes
#define KeccakP1600_AddBytesInLane oqs_sig_picnic_KeccakP1600_AddBytesInLane
#define KeccakP1600_AddLanes oqs_sig_picnic_KeccakP1600_AddLanes
#define KeccakP1600_ExtractAndAddBytes oqs_sig_picnic_KeccakP1600_ExtractAndAddBytes
#define KeccakP1600_ExtractAndAddBytesInLane oqs_sig_picnic_KeccakP1600_ExtractAndAddBytesInLane
#define KeccakP1600_ExtractAndAddLanes oqs_sig_picnic_KeccakP1600_ExtractAndAddLanes
#define KeccakP1600_ExtractBytes oqs_sig_picnic_KeccakP1600_ExtractBytes
#define KeccakP1600_ExtractBytesInLane oqs_sig_picnic_KeccakP1600_ExtractBytesInLane
#define KeccakP1600_ExtractLanes oqs_sig_picnic_KeccakP1600_ExtractLanes
#define KeccakP1600_Initialize oqs_sig_picnic_KeccakP1600_Initialize
#define KeccakP1600_OverwriteBytes oqs_sig_picnic_KeccakP1600_OverwriteBytes
#define KeccakP1600_OverwriteBytesInLane oqs_sig_picnic_KeccakP1600_OverwriteBytesInLane
#define KeccakP1600_OverwriteLanes oqs_sig_picnic_KeccakP1600_OverwriteLanes
#define KeccakP1600_OverwriteWithZeroes oqs_sig_picnic_KeccakP1600_OverwriteWithZeroes
#define KeccakP1600_Permute_24rounds oqs_sig_picnic_KeccakP1600_Permute_24rounds
#define KeccakP1600_Permute_Nrounds oqs_sig_picnic_KeccakP1600_Permute_Nrounds
#define KeccakWidth1600_Sponge oqs_sig_picnic_KeccakWidth1600_Sponge
#define KeccakWidth1600_SpongeAbsorb oqs_sig_picnic_KeccakWidth1600_SpongeAbsorb
#define KeccakWidth1600_SpongeAbsorbLastFewBits oqs_sig_picnic_KeccakWidth1600_SpongeAbsorbLastFewBits
#define KeccakWidth1600_SpongeInitialize oqs_sig_picnic_KeccakWidth1600_SpongeInitialize
#define KeccakWidth1600_SpongeInstance oqs_sig_picnic_KeccakWidth1600_SpongeInstance
#define KeccakWidth1600_SpongeSqueeze oqs_sig_picnic_KeccakWidth1600_SpongeSqueeze
#define Keccak_HashFinal oqs_sig_picnic_Keccak_HashFinal
#define Keccak_HashInitialize oqs_sig_picnic_Keccak_HashInitialize
#define Keccak_HashInstance oqs_sig_picnic_Keccak_HashInstance
#define Keccak_HashSqueeze oqs_sig_picnic_Keccak_HashSqueeze
#define Keccak_HashUpdate oqs_sig_picnic_Keccak_HashUpdate

#define picnic_get_lowmc_block_size oqs_sig_picnic_get_lowmc_block_size
#define picnic_get_param_name oqs_sig_picnic_get_param_name
#define picnic_get_private_key_size oqs_sig_picnic_get_private_key_size
#define picnic_get_public_key_size oqs_sig_picnic_get_public_key_size
#define picnic_keygen oqs_sig_picnic_keygen
#define picnic_read_private_key oqs_sig_picnic_read_private_key
#define picnic_read_public_key oqs_sig_picnic_read_public_key
#define picnic_sign oqs_sig_picnic_sign
#define picnic_signature_size oqs_sig_picnic_signature_size
#define picnic_sk_to_pk oqs_sig_picnic_sk_to_pk
#define picnic_validate_keypair oqs_sig_picnic_validate_keypair
#define picnic_verify oqs_sig_picnic_verify
#define picnic_write_private_key oqs_sig_picnic_write_private_key
#define picnic_write_public_key oqs_sig_picnic_write_public_key
#define picnic_instance_get oqs_sig_picnic_instance_get
#endif // OQS_NAMESPACE_PICNIC_H
