#include <quaternion.h>
#include <ec.h>
#include <endomorphism_action.h>
#include <id2iso.h>
#include <inttypes.h>
#include <locale.h>
#include <biextension.h>
#include <torsion_constants.h>

// helper function to apply a matrix to a basis of E[2^f]
// works in place
int
id2iso_matrix_application_even_basis(ec_basis_t *bas, const ec_curve_t *E, ibz_mat_2x2_t *mat, int f, bool last_point)
{
    digit_t scalars[2][NWORDS_ORDER] = { 0 };
    // int ret;

    ibz_t tmp, pow_two;
    ibz_init(&tmp);
    ibz_init(&pow_two);
    ibz_mul_2exp(&pow_two, &ibz_const_one, f);

    ec_basis_t tmp_bas;
    ec_copy_basis(&tmp_bas, bas);

    // reduction mod 2f
    ibz_mod(&mat->m[0][0], &mat->m[0][0], &pow_two);
    ibz_mod(&mat->m[0][1], &mat->m[0][1], &pow_two);
    ibz_mod(&mat->m[1][0], &mat->m[1][0], &pow_two);
    ibz_mod(&mat->m[1][1], &mat->m[1][1], &pow_two);

    // For a matrix [[a, c], [b, d]] we compute:
    //
    // first basis element R = [a]P + [b]Q
    ibz_to_digit_array(scalars[0], &mat->m[0][0]);
    ibz_to_digit_array(scalars[1], &mat->m[1][0]);
    ec_biscalar_mul(&bas->P, scalars[0], scalars[1], f, &tmp_bas, E);

    // second basis element S = [c]P + [d]Q
    ibz_to_digit_array(scalars[0], &mat->m[0][1]);
    ibz_to_digit_array(scalars[1], &mat->m[1][1]);
    ec_biscalar_mul(&bas->Q, scalars[0], scalars[1], f, &tmp_bas, E);

    if (last_point) {
        // Their difference R - S = [a - c]P + [b - d]Q
        ibz_sub(&tmp, &mat->m[0][0], &mat->m[0][1]);
        ibz_mod(&tmp, &tmp, &pow_two);
        ibz_to_digit_array(scalars[0], &tmp);
        ibz_sub(&tmp, &mat->m[1][0], &mat->m[1][1]);
        ibz_mod(&tmp, &tmp, &pow_two);
        ibz_to_digit_array(scalars[1], &tmp);
        ec_biscalar_mul(&bas->PmQ, scalars[0], scalars[1], f, &tmp_bas, E);
    }

    return 1;
}

// helper function to apply some endomorphism of E0 on the precomputed basis of E[2^f]
// works in place
void
id2iso_endomorphism_application_even_basis(ec_basis_t *bas,
                                           const ec_curve_t *E,
                                           const quat_alg_elem_t *theta,
                                           int f,
                                           bool last_point)
{
    ibz_t tmp;
    ibz_t two_e;
    ibz_init(&tmp);
    ibz_vec_4_t coeffs;
    ibz_vec_4_init(&coeffs);
    ibz_mat_2x2_t mat;
    ibz_mat_2x2_init(&mat);
    ibz_init(&two_e);

    ibz_t content;
    ibz_init(&content);

    // decomposing theta on the basis
    ibz_mul_2exp(&two_e, &ibz_const_one, f);
    quat_alg_make_primitive(&coeffs, &content, theta, &MAXORD_O0);
    for (int i = 0; i < 4; i++)
        ibz_mod(&coeffs.v[i], &coeffs.v[i], &two_e);
    assert(ibz_is_odd(&content));
    ibz_mod(&content, &content, &two_e);

    ibz_set(&mat.m[0][0], 0, 0);
    ibz_set(&mat.m[0][1], 0, 0);
    ibz_set(&mat.m[1][0], 0, 0);
    ibz_set(&mat.m[1][1], 0, 0);

    // computing the matrix

    for (uint8_t i = 0; i < 2; ++i) {
        ibz_add(&mat.m[i][i], &mat.m[i][i], &coeffs.v[0]);
        for (uint8_t j = 0; j < 2; ++j) {
            ibz_mul(&tmp, &CURVE_WITH_ENDOMORPHISMS.action_gen2.m[i][j], &coeffs.v[1]);
            ibz_add(&mat.m[i][j], &mat.m[i][j], &tmp);
            ibz_mod(&mat.m[i][j], &mat.m[i][j], &two_e);
            ibz_mul(&tmp, &CURVE_WITH_ENDOMORPHISMS.action_gen3.m[i][j], &coeffs.v[2]);
            ibz_add(&mat.m[i][j], &mat.m[i][j], &tmp);
            ibz_mod(&mat.m[i][j], &mat.m[i][j], &two_e);
            ibz_mul(&tmp, &CURVE_WITH_ENDOMORPHISMS.action_gen4.m[i][j], &coeffs.v[3]);
            ibz_add(&mat.m[i][j], &mat.m[i][j], &tmp);
            ibz_mod(&mat.m[i][j], &mat.m[i][j], &two_e);
            ibz_mul(&mat.m[i][j], &mat.m[i][j], &content);
            ibz_mod(&mat.m[i][j], &mat.m[i][j], &two_e);
        }
    }

    // and now we apply it
    id2iso_matrix_application_even_basis(bas, E, &mat, f, last_point);
}

// compute the ideal whose kernel is generated by vec2[0]*BO[0] + vec2[1]*B0[1] where B0 is the canonical basis of E0
void
id2iso_kernel_dlogs_to_ideal_even(quat_ideal_t *ideal, quat_alg_elem_t *split, const ibz_vec_2_t *vec2, int f)
{
    // algorithm: apply endomorphisms 1 and j+(1+k)/2 to the kernel point,
    // the result should form a basis of the respective torsion subgroup.
    // then apply i to the kernel point and decompose over said basis.
    // hence we have an equation a*P + b*[j+(1+k)/2]P == [i]P,
    // which will easily reveal an endomorphism that kills P.

    ibz_t two_pow;
    ibz_init(&two_pow);

    ibz_vec_2_t vec;
    ibz_vec_2_init(&vec);

    if (f == CHALLENGE_POWER) {
        ibz_copy(&two_pow, &TWO_TO_CHALLENGE_BITS);
    } else {
        ibz_mul_2exp(&two_pow, &ibz_const_one, f);
    }

    {
        ibz_mat_2x2_t mat;
        ibz_mat_2x2_init(&mat);

        ibz_copy(&mat.m[0][0], &vec2->v[0]);
        ibz_copy(&mat.m[1][0], &vec2->v[1]);

        ibz_mat_2x2_eval(&vec, &ACTION_J, vec2);
        ibz_copy(&mat.m[0][1], &vec.v[0]);
        ibz_copy(&mat.m[1][1], &vec.v[1]);

        ibz_mat_2x2_eval(&vec, &ACTION_GEN4, vec2);
        ibz_add(&mat.m[0][1], &mat.m[0][1], &vec.v[0]);
        ibz_add(&mat.m[1][1], &mat.m[1][1], &vec.v[1]);

        ibz_mod(&mat.m[0][1], &mat.m[0][1], &two_pow);
        ibz_mod(&mat.m[1][1], &mat.m[1][1], &two_pow);

        ibz_mat_2x2_t inv;
        ibz_mat_2x2_init(&inv);
        {
            int inv_ok UNUSED = ibz_mat_2x2_inv_mod(&inv, &mat, &two_pow);
            assert(inv_ok);
        }
        ibz_mat_2x2_eval(&vec, &ACTION_I, vec2);
        ibz_mat_2x2_eval(&vec, &inv, &vec);
        // reducing mod two_pow to avoid blowing-up the size for nothing
        ibz_mod(&vec.v[0], &vec.v[0], &two_pow);
        ibz_mod(&vec.v[1], &vec.v[1], &two_pow);
    }

    // final result: a - i + b*(j+(1+k)/2)
    ibz_t n;
    ibz_vec_4_t content;
    quat_alg_elem_t gen;
    quat_alg_elem_t split_test;
    quat_alg_elem_init(&gen);
    quat_alg_elem_init(&split_test);
    ibz_init(&n);
    ibz_vec_4_init(&content);
    ibz_set(&gen.denom, 2, 3);
    ibz_add(&gen.coord.v[0], &vec.v[0], &vec.v[0]);
    ibz_set(&gen.coord.v[1], -2, 3);
    ibz_add(&gen.coord.v[2], &vec.v[1], &vec.v[1]);
    ibz_copy(&gen.coord.v[3], &vec.v[1]);
    ibz_add(&gen.coord.v[0], &gen.coord.v[0], &vec.v[1]);

    // adjusting the bound on the coefficient of gen
    ibz_set_bound(&gen.coord.v[0], f + 10);
    ibz_set_bound(&gen.coord.v[1], f + 10);
    ibz_set_bound(&gen.coord.v[2], f + 10);
    ibz_set_bound(&gen.coord.v[3], f + 10);

    // we check if a - i + b* (j+(1+k) /2) is divisible by (1+i)
    quat_alg_elem_set(&split_test, 1, 1, 1, 0, 0);

    quat_alg_mul(&split_test, &gen, &split_test, &QUATALG_PINFTY);
    quat_alg_make_primitive(&content, &n, &split_test, &MAXORD_O0);
    // if that's the case we remove it by multiplying by (1 + i) / 2 and and recording (i-1) as the split part of the
    // challenge
    if (!ibz_is_odd(&n)) {
        ibz_vec_4_scalar_div(&split_test.coord, &n, &split_test.coord);
        quat_alg_elem_copy(&gen, &split_test);
        quat_alg_elem_set(split, 1, 1, -1, 0, 0);
        ibz_mul_2exp(&two_pow, &ibz_const_one, f - 1);

    } else {
        quat_alg_elem_set(split, 1, 1, 0, 0, 0);
    }

    int UNUSED even_creation = quat_ideal_create_O0_pow_two(ideal, &gen, &two_pow);
    assert(even_creation);

    assert(0 == ibz_cmp(&ideal->norm, &two_pow));
}

// finds mat such that:
// (mat*v).B2 = v.B1
// where "." is the dot product, defined as (v1,v2).(P,Q) = v1*P + v2*Q
// mat encodes the coordinates of the points of B1 in the basis B2
// specifically requires B1 or B2 to be "full" w.r.t to the 2^n torsion, so that we use tate
// full = 0 assumes B2 is "full" so the easier case.
// if we want to switch the role of B2 and B1, we invert the matrix, e.g. set full = 1
static void
id2iso_internal_change_of_basis_matrix_tate_impl(ibz_mat_2x2_t *mat,
                                                 const ec_basis_t *B1,
                                                 const ec_basis_t *B2,
                                                 ec_curve_t *E,
                                                 int f,
                                                 bool invert)
{
    digit_t x1[NWORDS_ORDER] = { 0 }, x2[NWORDS_ORDER] = { 0 }, x3[NWORDS_ORDER] = { 0 }, x4[NWORDS_ORDER] = { 0 };

#ifndef NDEBUG
    int e_full = TORSION_EVEN_POWER;
    int e_diff = e_full - f;
#endif

    // Ensure the input basis has points of order 2^f
    if (invert) {
        assert(test_basis_order_twof(B1, E, e_full));
        pairing_dlog_2_tate(x1, x2, x3, x4, B1, B2, E, f);
    } else {
        assert(test_basis_order_twof(B2, E, e_full));
        pairing_dlog_2_tate(x1, x2, x3, x4, B2, B1, E, f);
    }
    ibz_copy_digits(&(mat->m[0][0]), x1, NWORDS_ORDER);
    ibz_copy_digits(&(mat->m[1][0]), x2, NWORDS_ORDER);
    ibz_copy_digits(&(mat->m[0][1]), x3, NWORDS_ORDER);
    ibz_copy_digits(&(mat->m[1][1]), x4, NWORDS_ORDER);
    if (invert) {
        ibz_invmat(&(mat->m[0][0]), &(mat->m[1][0]), &(mat->m[0][1]), &(mat->m[1][1]), f);
    }

#ifndef NDEBUG
    {
        if (invert) {
            ec_point_t test, test2;
            ec_biscalar_mul(&test, (mat->m[0][0]).limbs, (mat->m[1][0]).limbs, f, B2, E);
            ec_dbl_iter(&test2, e_diff, &B1->P, E);
            assert(ec_is_equal(&test, &test2));

            ec_biscalar_mul(&test, (mat->m[0][1]).limbs, (mat->m[1][1]).limbs, f, B2, E);
            ec_dbl_iter(&test2, e_diff, &B1->Q, E);
            assert(ec_is_equal(&test, &test2));
        } else {
            ec_point_t test;
            ec_biscalar_mul(&test, (mat->m[0][0]).limbs, (mat->m[1][0]).limbs, f, B2, E);
            ec_dbl_iter(&test, e_diff, &test, E);
            assert(ec_is_equal(&test, &(B1->P)));

            ec_biscalar_mul(&test, (mat->m[0][1]).limbs, (mat->m[1][1]).limbs, f, B2, E);
            ec_dbl_iter(&test, e_diff, &test, E);
            assert(ec_is_equal(&test, &(B1->Q)));
        }
    }
#endif
}

void
id2iso_change_of_basis_matrix_tate(ibz_mat_2x2_t *mat, const ec_basis_t *B1, const ec_basis_t *B2, ec_curve_t *E, int f)
{
    id2iso_internal_change_of_basis_matrix_tate_impl(mat, B1, B2, E, f, false);
}

void
id2iso_change_of_basis_matrix_tate_invert(ibz_mat_2x2_t *mat,
                                          const ec_basis_t *B1,
                                          const ec_basis_t *B2,
                                          ec_curve_t *E,
                                          int f)
{
    id2iso_internal_change_of_basis_matrix_tate_impl(mat, B1, B2, E, f, true);
}
