#include "isog.h"
#include <assert.h>

// Degree-4 isogeny with kernel generated by P such that [2]P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void
iso_xisog_4(ec_kps4_t *kps, ec_point_t *B, const ec_point_t P)
{
    fp2_t t1, t2, t3, t4;

    fp2_sqr(&t1, &P.x);
    fp2_sqr(&t2, &P.z);

    fp2_add(&t3, &t2, &t1);
    fp2_sub(&t4, &t2, &t1);
    fp2_mul(&B->x, &t3, &t4);
    fp2_sqr(&B->z, &t2);

    // Constants for xeval_4
    fp2_add(&kps->K[2], &P.x, &P.z);
    fp2_sub(&kps->K[1], &P.x, &P.z);
    fp2_add(&t2, &t2, &t2);
    fp2_add(&kps->K[0], &t2, &t2);
}

// Degree-4 isogeny evaluation with kernel generated by P such that [2]P != (0, 0)
void
iso_xeval_4(ec_point_t *R, const ec_point_t *Q, const int lenQ, const ec_kps4_t *kps)
{
    fp2_t t0, t1;

    for (int i = 0; i < lenQ; i++) {
        fp2_add(&t0, &Q[i].x, &Q[i].z);
        fp2_sub(&t1, &Q[i].x, &Q[i].z);
        fp2_mul(&(R[i].x), &t0, &kps->K[1]);
        fp2_mul(&(R[i].z), &t1, &kps->K[2]);
        fp2_mul(&t0, &t0, &t1);
        fp2_mul(&t0, &t0, &kps->K[0]);
        fp2_add(&t1, &(R[i].x), &(R[i].z));
        fp2_sub(&(R[i].z), &(R[i].x), &(R[i].z));
        fp2_sqr(&t1, &t1);
        fp2_sqr(&(R[i].z), &(R[i].z));
        fp2_add(&(R[i].x), &t0, &t1);
        fp2_sub(&t0, &t0, &(R[i].z));
        fp2_mul(&(R[i].x), &(R[i].x), &t1);
        fp2_mul(&(R[i].z), &(R[i].z), &t0);
    }
}

// since we use degree 4 isogeny steps, we only allow 2^e-isogenies with even e
static uint32_t
iso_isogeny_2chain_with_strategy(ec_curve_t *curve, const ec_point_t *kernel, const int isog_len)
{
    ec_curve_normalize_A24(curve);
    ec_point_t A24;
    ec_copy_point(&A24, &curve->A24);

    int space = 1;
    for (int i = 1; i < isog_len; i *= 2)
        ++space;

    // Stack of remaining kernel points and their associated orders
    ec_point_t splits[space];
    uint16_t todo[space];
    splits[0] = *kernel;
    todo[0] = isog_len;

    // only 2^e-isogenies with e even are allowed
    assert(isog_len % 2 == 0);

    int current = 0; // Pointer to current top of stack

    // Chain of 4-isogenies
    for (int j = 0; j < isog_len / 2 - 1; ++j) {
        assert(current >= 0);
        assert(todo[current] >= 1);
        // Get the next point of order 4
        while (todo[current] != 2) {
            assert(todo[current] >= 3);
            // A new split will be added
            ++current;
            assert(current < space);
            // We set the seed of the new split to be computed and saved
            ec_copy_point(&splits[current], &splits[current - 1]);
            // if we copied from the very first element, then we perform one additional doubling
            unsigned num_dbls = todo[current - 1] / 4 * 2 + todo[current - 1] % 2;
            todo[current] = todo[current - 1] - num_dbls;
            while (num_dbls--)
                ec_xDBL_A24(&splits[current], &splits[current], &A24, false);
        }

        if (j == 0) {
            assert(fp2_is_one(&A24.z));
            if (!ec_is_four_torsion(&splits[current], curve))
                return -1;

            ec_point_t T;
            ec_xDBL_A24(&T, &splits[current], &A24, false);
            if (fp2_is_zero(&T.x)) {
                debug_print("Kernel above a canonical 4 torsion point !\n");
                return -1; // special isogenies not allowed
            }
        } else {
            assert(todo[current] == 2);
#ifndef NDEBUG
            if (fp2_is_zero(&splits[current].z))
                debug_print("splitting point z coordinate is unexpectedly zero");

            ec_point_t test;
            ec_xDBL_A24(&test, &splits[current], &A24, false);
            if (fp2_is_zero(&test.z))
                debug_print("z coordinate is unexpectedly zero before doubling");
            ec_xDBL_A24(&test, &test, &A24, false);
            if (!fp2_is_zero(&test.z))
                debug_print("z coordinate is unexpectedly not zero after doubling");
#endif
        }

        // Evaluate 4-isogeny
        ec_kps4_t kps4;
        iso_xisog_4(&kps4, &A24, splits[current]);
        iso_xeval_4(splits, splits, current, &kps4);
        for (int i = 0; i < current; ++i)
            todo[i] -= 2;

        --current;
    }
    assert(isog_len % 2 ? !current : current == 0);

    if (!ec_normalize_montgomery(curve, &splits[current], NULL))
        return -1;

    return 0;
}

uint32_t
iso_isogeny_2chain(ec_curve_t *image, ec_isog_even_t *phi)
{
    ec_copy_curve(image, &phi->curve);
    return iso_isogeny_2chain_with_strategy(image, &phi->kernel, phi->length);
}
