#include <signature.h>
#include <tools.h>
#include <quaternion_data.h>
#include <id2iso.h>
#include <torsion_constants.h>
#include <encoded_sizes.h>
#include <mp.h>
#include <endomorphism_action.h>
#include <fp_constants.h>
#include <prng.h>

// compute the commitment with ideal to isogeny
// and apply it to the basis of E0 (together with the multiplication by some scalar u)
static bool
commit(ec_curve_t *E_com, ec_basis_t *basis_even_com, quat_ideal_t *ideal_com, prng_domain_ctx_t *prng_commit_domain)
{
    bool found = false;

    found = quat_random_ideal_O0_given_prime_norm(ideal_com, &COM_DEGREE, prng_commit_domain);
    assert(found);

    // replacing it with a shorter prime norm equivalent ideal
    found =
        found && quat_ideal_small_equivalent_coprime(NULL, ideal_com, ideal_com, &ibz_const_two, prng_commit_domain);
    found = found && dim2id2iso_arbitrary_isogeny_evaluation(basis_even_com, E_com, ideal_com);
    return found;
}

static void
compute_challenge_ideal_signature(quat_ideal_t *ideal_chall_two,
                                  quat_alg_elem_t *chall_split,
                                  const signature_t *sig,
                                  const secret_key_t *sk)
{
    ibz_vec_2_t vec;
    ibz_vec_2_init(&vec);

    // vec is a vector [1, chall_coeff] coefficients encoding the kernel of the challenge isogeny as
    // B[0] + chall_coeff*B[1] where B is the canonical basis of the 2^TORSION_EVEN_POWER torsion of EA
    ibz_set(&vec.v[0], 1, 2);
    ibz_copy_digits(&vec.v[1], sig->chall_coeff, NWORDS_ORDER);

    // now we compute the ideal associated to the challenge
    // for that, we need to find vec such that the kernel of the challenge isogeny is generated by
    // vec[0]*B0[0] + vec[1]*B0[1] where B0 is the image through the secret key isogeny of the canonical basis E0
    ibz_mat_2x2_eval(&vec, &sk->mat_BAcan_to_BA0_two, &vec);

    // ideal_chall_two is the pullback of the ideal challenge through the secret key ideal
    id2iso_kernel_dlogs_to_ideal_even(ideal_chall_two, chall_split, &vec, CHALLENGE_BITS);

    // assert(ibz_cmp(&ideal_chall_two->norm, &TWO_TO_CHALLENGE_BITS) == 0);
}

static int
compute_dim2_isogeny_challenge(theta_couple_curve_with_basis_t *codomain,
                               theta_couple_curve_with_basis_t *domain,
                               const ibz_t *degree_resp_inv)
{
    // now, we compute the isogeny Phi : Ecom x Eaux -> Echl' x Eaux'
    // where Echl' is 2^exp_diadic_val_full_resp isogenous to Echal
    // ker Phi = <(Bcom_can.P,Baux.P),(Bcom_can.Q,Baux.Q)>

    // preparing the domain
    int reduced_order = RESPONSE_BITS + HD_EXTRA_TORSION;
    theta_couple_curve_t EcomXEaux;
    ec_copy_curve(&EcomXEaux.E1, &domain->E1);
    ec_copy_curve(&EcomXEaux.E2, &domain->E2);

    // preparing the kernel
    theta_kernel_couple_points_t dim_two_ker;
    theta_copy_bases_to_kernel(&dim_two_ker, &domain->B1, &domain->B2);

    // dividing by the degree of the response
    digit_t scalar[NWORDS_ORDER];
    ibz_to_digit_array(scalar, degree_resp_inv);
    ec_mul(&dim_two_ker.T1.P2, scalar, reduced_order, &dim_two_ker.T1.P2, &EcomXEaux.E2);
    ec_mul(&dim_two_ker.T2.P2, scalar, reduced_order, &dim_two_ker.T2.P2, &EcomXEaux.E2);

    theta_couple_point_t pushed_points[3];
    theta_couple_point_t *const Tev1 = pushed_points + 0, *const Tev2 = pushed_points + 1,
                                *const Tev1m2 = pushed_points + 2;

    // Set points on the commitment curve
    ec_copy_point(&Tev1->P1, &domain->B1.P);
    ec_copy_point(&Tev2->P1, &domain->B1.Q);
    ec_copy_point(&Tev1m2->P1, &domain->B1.PmQ);

    // Zero points on the aux curve
    ec_point_init(&Tev1->P2);
    ec_point_init(&Tev2->P2);
    ec_point_init(&Tev1m2->P2);

    theta_couple_curve_t codomain_product;

    // computation of the dim2 isogeny
    if (!theta_chain_compute_and_eval(RESPONSE_BITS,
                                      &EcomXEaux,
                                      &dim_two_ker,
                                      &codomain_product,
                                      pushed_points,
                                      sizeof(pushed_points) / sizeof(*pushed_points)))
        return 0;

    assert(test_couple_point_order_twof(Tev1, &codomain_product, reduced_order));

    // Set the auxiliary curve
    ec_copy_curve(&codomain->E1, &codomain_product.E2);

    // Set the codomain curve from the dim 2 isogeny
    // it should always be the first curve
    ec_copy_curve(&codomain->E2, &codomain_product.E1);

    // Set the evaluated basis pointsdim2_isogeny_chall
    ec_copy_point(&codomain->B1.P, &Tev1->P2);
    ec_copy_point(&codomain->B1.Q, &Tev2->P2);
    ec_copy_point(&codomain->B1.PmQ, &Tev1m2->P2);

    ec_copy_point(&codomain->B2.P, &Tev1->P1);
    ec_copy_point(&codomain->B2.Q, &Tev2->P1);
    ec_copy_point(&codomain->B2.PmQ, &Tev1m2->P1);
    return 1;
}

static void
set_aux_curve_signature(signature_t *sig, ec_curve_t *E_aux)
{
    ec_normalize_curve(E_aux);
    fp2_copy(&sig->E_aux_A, &E_aux->A);
}

static void
compute_and_set_basis_change_matrix(signature_t *sig,
                                    const ec_basis_t *B_aux_2,
                                    ec_basis_t *B_chall_2,
                                    ec_curve_t *E_aux_2,
                                    ec_curve_t *E_chall,
                                    int f)
{
    // Matrices for change of bases matrices
    ibz_mat_2x2_t mat_Baux2_to_Baux2_can, mat_Bchall_can_to_Bchall;
    ibz_mat_2x2_init(&mat_Baux2_to_Baux2_can);
    ibz_mat_2x2_init(&mat_Bchall_can_to_Bchall);

    // Compute canonical bases
    ec_basis_t B_can_chall, B_aux_2_can;
    sig->hint_chall = ec_curve_to_basis_2f_to_hint(&B_can_chall, E_chall, TORSION_EVEN_POWER, f);
    sig->hint_aux = ec_curve_to_basis_2f_to_hint(&B_aux_2_can, E_aux_2, TORSION_EVEN_POWER, f);

#ifndef NDEBUG
    {
        // Ensure all points have the desired order
        assert(test_basis_order_twof(&B_aux_2_can, E_aux_2, TORSION_EVEN_POWER));
        assert(test_basis_order_twof(B_aux_2, E_aux_2, f));
    }
#endif

    // compute the matrix to go from B_aux_2 to B_aux_2_can
    id2iso_change_of_basis_matrix_tate_invert(&mat_Baux2_to_Baux2_can, &B_aux_2_can, B_aux_2, E_aux_2, f);

    // apply the change of basis to B_chall_2
    id2iso_matrix_application_even_basis(B_chall_2, E_chall, &mat_Baux2_to_Baux2_can, f, true);

#ifndef NDEBUG
    {
        // Ensure all points have the desired order
        assert(test_basis_order_twof(&B_can_chall, E_chall, TORSION_EVEN_POWER));
    }
#endif

    // compute the matrix to go from B_chall_can to B_chall_2
    id2iso_change_of_basis_matrix_tate(&mat_Bchall_can_to_Bchall, B_chall_2, &B_can_chall, E_chall, f);

    // normalize the matrix (modulo sign)
    ibz_mat_2x2_normalize(&mat_Bchall_can_to_Bchall, f);

    // Assert all values in the matrix are of the expected size for packing
    assert(f == RESPONSE_BITS + HD_EXTRA_TORSION);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall.m[0][0]) <= f);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall.m[0][1]) <= f);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall.m[1][0]) <= f);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall.m[1][1]) <= f);

    // Set the basis change matrix to signature
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[0][0], &(mat_Bchall_can_to_Bchall.m[0][0]));
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[0][1], &(mat_Bchall_can_to_Bchall.m[0][1]));
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[1][0], &(mat_Bchall_can_to_Bchall.m[1][0]));
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[1][1], &(mat_Bchall_can_to_Bchall.m[1][1]));

    // Finalise the matrices
}

int
protocols_sign(signature_t *sig, const public_key_t *pk, secret_key_t *sk, const unsigned char *m, size_t l)
{
    if (prng_seed() != 0)
        return 0;

    int ret = 0;
    int reduced_order = RESPONSE_BITS + HD_EXTRA_TORSION;
    quat_alg_elem_t resp_aux_quat;
    quat_ideal_t ideal_skchall;
    quat_alg_elem_t aux_split;
    quat_alg_elem_t chall_split;
    quat_ideal_t aux_ideal;
    quat_ideal_init(&ideal_skchall);
    quat_alg_elem_init(&aux_split);
    quat_ideal_init(&aux_ideal);
    quat_alg_elem_init(&resp_aux_quat);
    quat_alg_elem_init(&chall_split);

    // assert(RESPONSE_BITS <= (intmax_t)UINT_FAST8_MAX); // otherwise we might need more bits there

    ibz_t remain, lattice_content, random_aux_norm, degree_resp_inv, deg_odd, tmp_int, tmp_int2;
    ibz_init(&remain);
    ibz_init(&tmp_int);
    ibz_init(&tmp_int2);
    ibz_init(&lattice_content);
    ibz_init(&random_aux_norm);
    ibz_init(&degree_resp_inv);
    ibz_init(&deg_odd);

    quat_alg_elem_t resp_quat;
    quat_alg_elem_init(&resp_quat);

    quat_ideal_t ideal_commit, ideal_skchall_aux;
    quat_ideal_init(&ideal_commit);
    quat_ideal_init(&ideal_skchall_aux);

    // This structure holds two curves E1 x E2 together with a basis Bi of E[2^n] for each of these curves

    // theta_couple_curve_t Ecom_Eaux;

    theta_couple_curve_with_basis_t Ecom_Eaux;
    // This structure holds two curves E1 x E2 together with a basis Bi of Ei[2^n]
    theta_couple_curve_with_basis_t Eaux2_Echall2;

    // This will hold the challenge curve
    // ec_curve_t E_chall = sk->curve;

    ec_curve_init(&Ecom_Eaux.E1);
    ec_curve_init(&Ecom_Eaux.E2);

    prng_domain_ctx_t prng_commit_domain;
    prng_domain_seed(&prng_commit_domain, DS_COMMITMENT_DOMAIN);

    // computing the commitment
    ret = commit(&Ecom_Eaux.E1, &Ecom_Eaux.B1, &ideal_commit, &prng_commit_domain);
    prng_domain_clear(&prng_commit_domain);
    // should never fail
    assert(ret);
    if (!ret)
        goto err;

    // Hash the message to a kernel generator i.e. a scalar such that ker = P + [s]Q
    hash_to_challenge(&sig->chall_coeff, pk, &Ecom_Eaux.E1, m, l);
    // Compute the challenge ideal and response quaternion element
    {
        quat_ideal_t ideal_chall_two;
        quat_alg_elem_t sk_chall_quat;
        quat_alg_elem_init(&sk_chall_quat);
        quat_ideal_init(&ideal_chall_two);

        // computing the challenge ideal
        compute_challenge_ideal_signature(&ideal_chall_two, &chall_split, sig, sk);

        prng_domain_ctx_t prng_resp_domain;
        prng_domain_seed(&prng_resp_domain, DS_RESPONSE_DOMAIN);
        quat_response_element(&ideal_skchall,
                              &resp_quat,
                              &deg_odd,
                              &sk_chall_quat,
                              &sk->secret_ideal,
                              &ideal_chall_two,
                              &chall_split,
                              &ideal_commit,
                              &prng_resp_domain,
                              RESPONSE_BITS - 1);
        ibz_gcd(&tmp_int, &ideal_skchall.norm, &ideal_commit.norm);
        if (!ibz_is_one(&tmp_int)) {
            ret = 0;
            fprintf(
                stderr,
                "Non-coprime resp norms. This should never happen. Please report this failure to the developers.\n");
            // Clean up
            prng_domain_clear(&prng_resp_domain);
            goto err;
        }
        // compute aux norm
        ibz_mul_2exp(&remain, &ibz_const_one, RESPONSE_BITS);
        ibz_sub(&random_aux_norm, &remain, &deg_odd);
        ibz_set_bound(&random_aux_norm, RESPONSE_BITS + 1);

        // multiplying by 2^HD_EXTRA_TORSION to account for the fact that
        // we use extra torsion above the kernel
        ibz_mul_2exp(&remain, &remain, HD_EXTRA_TORSION);
        // sample aux
        if (!quat_random_ideal_O0_given_arbitrary_odd_norm(
                &aux_ideal, &aux_split, &random_aux_norm, &sk_chall_quat, &prng_resp_domain)) {
            ret = 0;
            // Clean up
            prng_domain_clear(&prng_resp_domain);
            goto err;
        }
        // Clean up
        prng_domain_clear(&prng_resp_domain);

        // Catch errors from negligible non-coprimality events
        ibz_gcd(&tmp_int, &aux_ideal.norm, &ideal_skchall.norm);
        ibz_gcd(&tmp_int2, &aux_ideal.norm, &sk->secret_ideal.norm);
        if (!ibz_is_one(&tmp_int) || !ibz_is_one(&tmp_int2)) {
            ret = 0;
            fprintf(stderr,
                    "Non-coprime aux norms. This should never happen. Please report this failure to the developers.\n");
            goto err;
        }
        quat_ideal_intersect_O0(&ideal_skchall_aux, &aux_ideal, &ideal_skchall, &aux_split);
    }
    {
        ibz_t d1, d2, u, v;
        quat_alg_elem_t b1, b2;
        quat_alg_elem_init(&b1);
        quat_alg_elem_init(&b2);
        ibz_init(&d1);
        ibz_init(&d2);
        ibz_init(&u);
        ibz_init(&v);
        // Id2iso
        int UNUSED qlapoty =
            dim2id2iso_ideal_to_isogeny_qlapoty(&b1, &d1, &Ecom_Eaux.E2, &Ecom_Eaux.B2, &ideal_skchall_aux);
        assert(qlapoty);

        // apply matrix
        ibz_invmod(&degree_resp_inv, &ideal_skchall.norm, &remain);
        ibz_mul(&aux_split.coord.v[0], &aux_split.coord.v[0], &degree_resp_inv);
        ibz_mod(&aux_split.coord.v[0], &aux_split.coord.v[0], &remain);
        ibz_mul(&aux_split.coord.v[1], &aux_split.coord.v[1], &degree_resp_inv);
        ibz_mod(&aux_split.coord.v[1], &aux_split.coord.v[1], &remain);
        ibz_set_bound(&aux_split.coord.v[2], ibz_get_bound(&remain));
        ibz_set_bound(&aux_split.coord.v[3], ibz_get_bound(&remain));
        quat_alg_mul(&resp_aux_quat, &aux_split, &resp_quat, &QUATALG_PINFTY);
        id2iso_endomorphism_application_even_basis(&Ecom_Eaux.B2, &Ecom_Eaux.E2, &resp_aux_quat, TORSION_EVEN_POWER, 0);

#ifndef NDEBUG
        // testing that the order of the points in the bases is as expected
        assert(test_basis_order_twof(&Ecom_Eaux.B1, &Ecom_Eaux.E1, TORSION_EVEN_POWER));
        assert(test_basis_order_twof(&Ecom_Eaux.B2, &Ecom_Eaux.E2, TORSION_EVEN_POWER));
#endif

        // applying the matrix to compute Baux
        // first, we reduce to the relevant order
        ec_dbl_iter_basis(&Ecom_Eaux.B1, TORSION_EVEN_POWER - reduced_order, &Ecom_Eaux.B1, &Ecom_Eaux.E1);
        ec_dbl_iter_basis(&Ecom_Eaux.B2, TORSION_EVEN_POWER - reduced_order, &Ecom_Eaux.B2, &Ecom_Eaux.E2);

        // Given all the above data, compute a dim two isogeny with domain
        // E_com x E_aux
        // and codomain
        // E_aux_2 x E_chall_2 (note: E_chall_2 is isomorphic to E_chall)
        // and evaluated points stored as bases in
        // B_aux_2 on E_aux_2
        // B_chall_2 on E_chall_2
        ibz_invmod(&degree_resp_inv, &deg_odd, &remain);
        ret = compute_dim2_isogeny_challenge(&Eaux2_Echall2, &Ecom_Eaux, &degree_resp_inv);
        assert(ret);
        if (!ret)
            goto err;
    }

    // Set to the signature the Montgomery A-coefficient of E_aux_2
    set_aux_curve_signature(sig, &Eaux2_Echall2.E1);

    // Set the basis change matrix from canonical bases to the supplied bases
    compute_and_set_basis_change_matrix(
        sig, &Eaux2_Echall2.B1, &Eaux2_Echall2.B2, &Eaux2_Echall2.E1, &Eaux2_Echall2.E2, reduced_order);
err:;
    prng_clear();
    return ret;
}
