#define OQS_COMPILE_BUILD_TARGET "x86_64-apple-darwin18.7.0"
#define OQS_COMPILE_CFLAGS "-g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -I/usr/local/opt/openssl/include  -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized  -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/Users/abcd/Documents/liboqs/include -I.  -I/usr/local/opt/openssl/include  -O3  -fomit-frame-pointer  -DCONSTANT_TIME "
#define OQS_COMPILE_LDFLAGS " -L/usr/local/opt/openssl/lib"
/*#define OQS_ENABLE_KEM_bike1_l1 1
#define OQS_ENABLE_KEM_bike1_l3 1
#define OQS_ENABLE_KEM_bike1_l5 1
#define OQS_ENABLE_KEM_bike2_l1 1
#define OQS_ENABLE_KEM_bike2_l3 1
#define OQS_ENABLE_KEM_bike2_l5 1
#define OQS_ENABLE_KEM_bike3_l1 1
#define OQS_ENABLE_KEM_bike3_l3 1
#define OQS_ENABLE_KEM_bike3_l5 1*/
#define OQS_ENABLE_KEM_frodokem_1344_aes 1
#define OQS_ENABLE_KEM_frodokem_1344_shake 1
#define OQS_ENABLE_KEM_frodokem_640_aes 1
#define OQS_ENABLE_KEM_frodokem_640_shake 1
#define OQS_ENABLE_KEM_frodokem_976_aes 1
#define OQS_ENABLE_KEM_frodokem_976_shake 1
#define OQS_ENABLE_KEM_kyber_1024 1
#define OQS_ENABLE_KEM_kyber_512 1
#define OQS_ENABLE_KEM_kyber_768 1
/*#define OQS_ENABLE_KEM_newhope_1024cca 1
#define OQS_ENABLE_KEM_newhope_512cca 1
#define OQS_ENABLE_KEM_ntru_hps2048509 1
#define OQS_ENABLE_KEM_ntru_hps2048677 1
#define OQS_ENABLE_KEM_ntru_hps4096821 1
#define OQS_ENABLE_KEM_ntru_hrss701 1
#define OQS_ENABLE_KEM_saber_firesaber 1
#define OQS_ENABLE_KEM_saber_lightsaber 1
#define OQS_ENABLE_KEM_saber_saber 1
#define OQS_ENABLE_KEM_sidh_p434 1
#define OQS_ENABLE_KEM_sidh_p503 1
#define OQS_ENABLE_KEM_sidh_p610 1
#define OQS_ENABLE_KEM_sidh_p751 1
#define OQS_ENABLE_KEM_sike_p434 1
#define OQS_ENABLE_KEM_sike_p503 1
#define OQS_ENABLE_KEM_sike_p610 1
#define OQS_ENABLE_KEM_sike_p751 1*/
#define OQS_ENABLE_SIG_dilithium_2 1
#define OQS_ENABLE_SIG_dilithium_3 1
#define OQS_ENABLE_SIG_dilithium_4 1
#define OQS_ENABLE_SIG_mqdss_31_48 1
#define OQS_ENABLE_SIG_mqdss_31_64 1
#define OQS_ENABLE_SIG_picnic2_L1_FS 1
#define OQS_ENABLE_SIG_picnic2_L3_FS 1
#define OQS_ENABLE_SIG_picnic2_L5_FS 1
#define OQS_ENABLE_SIG_picnic_L1_FS 1
#define OQS_ENABLE_SIG_picnic_L1_UR 1
#define OQS_ENABLE_SIG_picnic_L3_FS 1
#define OQS_ENABLE_SIG_picnic_L3_UR 1
#define OQS_ENABLE_SIG_picnic_L5_FS 1
#define OQS_ENABLE_SIG_picnic_L5_UR 1
#define OQS_ENABLE_SIG_qTESLA_I 1
#define OQS_ENABLE_SIG_qTESLA_III_size 1
#define OQS_ENABLE_SIG_qTESLA_III_speed 1
#define OQS_ENABLE_SIG_sphincs_haraka_128f_robust 1
#define OQS_ENABLE_SIG_sphincs_haraka_128f_simple 1
#define OQS_ENABLE_SIG_sphincs_haraka_128s_robust 1
#define OQS_ENABLE_SIG_sphincs_haraka_128s_simple 1
#define OQS_ENABLE_SIG_sphincs_haraka_192f_robust 1
#define OQS_ENABLE_SIG_sphincs_haraka_192f_simple 1
#define OQS_ENABLE_SIG_sphincs_haraka_192s_robust 1
#define OQS_ENABLE_SIG_sphincs_haraka_192s_simple 1
#define OQS_ENABLE_SIG_sphincs_haraka_256f_robust 1
#define OQS_ENABLE_SIG_sphincs_haraka_256f_simple 1
#define OQS_ENABLE_SIG_sphincs_haraka_256s_robust 1
#define OQS_ENABLE_SIG_sphincs_haraka_256s_simple 1
#define OQS_ENABLE_SIG_sphincs_sha256_128f_robust 1
#define OQS_ENABLE_SIG_sphincs_sha256_128f_simple 1
#define OQS_ENABLE_SIG_sphincs_sha256_128s_robust 1
#define OQS_ENABLE_SIG_sphincs_sha256_128s_simple 1
#define OQS_ENABLE_SIG_sphincs_sha256_192f_robust 1
#define OQS_ENABLE_SIG_sphincs_sha256_192f_simple 1
#define OQS_ENABLE_SIG_sphincs_sha256_192s_robust 1
#define OQS_ENABLE_SIG_sphincs_sha256_192s_simple 1
#define OQS_ENABLE_SIG_sphincs_sha256_256f_robust 1
#define OQS_ENABLE_SIG_sphincs_sha256_256f_simple 1
#define OQS_ENABLE_SIG_sphincs_sha256_256s_robust 1
#define OQS_ENABLE_SIG_sphincs_sha256_256s_simple 1
#define OQS_ENABLE_SIG_sphincs_shake256_128f_robust 1
#define OQS_ENABLE_SIG_sphincs_shake256_128f_simple 1
#define OQS_ENABLE_SIG_sphincs_shake256_128s_robust 1
#define OQS_ENABLE_SIG_sphincs_shake256_128s_simple 1
#define OQS_ENABLE_SIG_sphincs_shake256_192f_robust 1
#define OQS_ENABLE_SIG_sphincs_shake256_192f_simple 1
#define OQS_ENABLE_SIG_sphincs_shake256_192s_robust 1
#define OQS_ENABLE_SIG_sphincs_shake256_192s_simple 1
#define OQS_ENABLE_SIG_sphincs_shake256_256f_robust 1
#define OQS_ENABLE_SIG_sphincs_shake256_256f_simple 1
#define OQS_ENABLE_SIG_sphincs_shake256_256s_robust 1
#define OQS_ENABLE_SIG_sphincs_shake256_256s_simple 1
/* #undef OQS_KEM_BIKE_ADDITIONAL_IMPLEMENTATION */
#define OQS_KEM_DEFAULT OQS_KEM_alg_frodokem_640_aes
#define OQS_MASTER_BRANCH /**/
#define OQS_SIG_DEFAULT OQS_SIG_alg_dilithium_2
#define OQS_VERSION_NUMBER 0x00200000L
#define OQS_VERSION_TEXT "0.2.0-dev"
/* #undef USE_AES_C */
#define USE_AES_INSTRUCTIONS 1
#define USE_AES_OPENSSL 1
#define USE_AVX2_INSTRUCTIONS 1
/* #undef USE_AVX512F_INSTRUCTIONS */
#define USE_AVX_INSTRUCTIONS 1
#define USE_BMI_INSTRUCTIONS 1
/* #undef USE_FMA4_INSTRUCTIONS */
#define USE_FMA_INSTRUCTIONS 1
#define USE_MMX_INSTRUCTIONS 1
#define USE_OPENSSL 1
#define USE_POPCNT_INSTRUCTIONS 1
/* #undef USE_SHA2_C */
#define USE_SHA2_OPENSSL 1
#define USE_SHA3_C 1
/* #undef USE_SHA3_OPENSSL */
#define USE_SSE2_INSTRUCTIONS 1
#define USE_SSE3_INSTRUCTIONS 1
/* #undef USE_SSE4A_INSTRUCTIONS */
#define USE_SSE4_1_INSTRUCTIONS 1
#define USE_SSE4_2_INSTRUCTIONS 1
#define USE_SSE_INSTRUCTIONS 1
