sudo: false
dist: trusty

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl-2/

# Only build master, the version branches (e.g. 1.7.x), and
# version tags (which are apparently considered branches by travis)
branches:
    only:
        - master
        - /\d+\.\d+\.x/
        - /\d+\.\d+(\.\d+)?/

matrix:
    include:
        # these are just to make travis's UI a bit prettier
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: pypy-5.3
          env: TOXENV=pypy-nocoverage
        - python: pypy2.7-5.10.0
          env: TOXENV=pypy-nocoverage
        - python: pypy3.5-5.10.1
          env: TOXENV=pypy3-nocoverage
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.0i
        - python: 3.5
          env: TOXENV=py35 OPENSSL=1.1.0i
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.1-pre9
        - python: 3.7
          env: TOXENV=py37 OPENSSL=1.1.1-pre9
          dist: xenial
          sudo: true
        - python: 3.7
          env: TOXENV=py37 LIBRESSL=2.4.5
          dist: xenial
          sudo: true
        - python: 3.7
          env: TOXENV=py37 LIBRESSL=2.6.5
          dist: xenial
          sudo: true
        - python: 3.7
          env: TOXENV=py37 LIBRESSL=2.7.4
          dist: xenial
          sudo: true
        - python: 3.6
          env: TOXENV=docs OPENSSL=1.1.0i
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.4
          env: TOXENV=py3pep8

        - python: 2.7
          env: DOWNSTREAM=pyopenssl
        - python: 2.7
          env: DOWNSTREAM=twisted
        - python: 2.7
          env: DOWNSTREAM=paramiko
        - python: 2.7
          env: DOWNSTREAM=aws-encryption-sdk
        - python: 2.7
          env: DOWNSTREAM=dynamodb-encryption-sdk OPENSSL=1.1.0i
        - python: 2.7
          env: DOWNSTREAM=certbot OPENSSL=1.1.0i
        - python: 2.7
          env: DOWNSTREAM=certbot-josepy
        - python: 2.7
          env: DOWNSTREAM=urllib3

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            # This is set to a secure variable to prevent forks from notifying the
            # IRC channel whenever they fail a build. This can be removed when travis
            # implements https://github.com/travis-ci/travis-ci/issues/1094.
            # The value encrypted here was created via
            # travis encrypt "irc.freenode.org#cryptography-dev"
            - secure: "A93qvTOlwlMK5WoEvZQ5jQ8Z4Hd0JpeO53WYt8iIJ3s/L6AubkfiN7gwhThRtPnPx7DVMenoKRMlcRg76/ICvXEViVnGgXFjsypF0CzVcIay9pPdjpZjZHP735yLfX512RtxYEdEGwi5r25Z2CEFaydhhxNwfuMxGBtLUjusix4="
        use_notice: true
        skip_join: true
