name: ARM64 github

on: workflow_dispatch

jobs:
  ry-arm:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: |
          docker run -it -v `pwd`:/root/project \
                         openquantumsafe/ci-ubuntu-focal-arm64:latest bash \
                         -c 'cd /root/project && \
                             uname -a && \
                             mkdir build && cd build && source ~/.bashrc && \
                             cmake -GNinja -DOQS_STRICT_WARNINGS=ON $CMAKE_ARGS .. && cmake -LA .. && ninja && \
                             cd .. && mkdir -p tmp && \
                             python3 -m pytest --verbose \
                                               --ignore=tests/test_code_conventions.py \
                                               --junitxml=build/test-results/pytest/test-results.xml $PYTEST_ARGS'
