name: ct-tooling

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  interactive-inputs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Install Python deps
        run: python -m pip install pytest requests

      - name: Generate algorithm list
        id: set
        run: |
          python3 - <<'PY'
          import os, sys
          sys.path.insert(0, 'tests')
          import helpers
          algs = helpers.available_kems_by_name() + helpers.available_sigs_by_name()
          interactive_yaml = (
              "fields:\n"
              "  - label: runtime-options\n"
              "    properties:\n"
              "      description: Choose one or more algorithms to execute constant-time testing on\n"
              "      display: Select the algorithm(s) to execute constant-time testing on\n"
              "      type: multiselect\n"
              "      choices:\n"
          )
          for a in algs:
              interactive_yaml += f"        - {a}\n"
          interactive_yaml += "      required: true\n"
          with open(os.environ['GITHUB_OUTPUT'], 'a') as gout:
              gout.write('interactive<<EOF\n')
              gout.write(interactive_yaml)
              gout.write('EOF\n')
          PY

      - name: Example Interactive Inputs Step
        id: interactive-inputs
        uses: boasiHQ/interactive-inputs@v2
        with:
          timeout: 300
          title: Select algorithm(s) for CT Testing
          interactive: ${{ steps.set.outputs.interactive }}
          notifier-slack-enabled: "false"
          notifier-discord-enabled: "false"
          github-token: ${{ github.token }}
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
    outputs:
      runtime-options: ${{ steps.interactive-inputs.outputs.runtime-options }}

  valgrind-varlat:
    needs: [interactive-inputs]
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        liboqs_build: [generic, auto]
        opt_flag: [-O0, -O1, -O2, -O3, -Os, -Ofast, "-O2 -fno-tree-vectorize", "-O3 -fno-tree-vectorize"]
        exclude:
          - compiler: clang
            opt_flag: "-O2 -fno-tree-vectorize"
          - compiler: clang
            opt_flag: "-O3 -fno-tree-vectorize"
        include:
          - compiler: clang
            liboqs_build: generic
            opt_flag: "-O2 -fno-vectorize"
          - compiler: clang
            liboqs_build: auto
            opt_flag: "-O2 -fno-vectorize"
          - compiler: clang
            liboqs_build: generic
            opt_flag: "-O3 -fno-vectorize"
          - compiler: clang
            liboqs_build: auto
            opt_flag: "-O3 -fno-vectorize"
      max-parallel: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Build valgrind_varlat
        shell: bash
        run: |
          set -eu -o pipefail
          INSTALL_PREFIX="$PWD/valgrind_varlat"

          echo "Cloning Valgrind's source code"
          git clone git://sourceware.org/git/valgrind.git valgrind_varlat_src> /dev/null 2>&1
          cd valgrind_varlat_src
          git checkout 112f1080b7c21e37dfce0a2e589d0dc7aa115afa > /dev/null 2>&1

          echo "Applying Kyberslash patch"
          git apply "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/valgrind-try-patch-20250805.txt" > /dev/null 2>&1
          git apply "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/valgrind-varlat-patch-20250805.txt" > /dev/null 2>&1
          git apply "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/valgrind-varlat-sup-block.txt" > /dev/null 2>&1

          echo "Building Valgrind-Varlat"
          ./autogen.sh > /dev/null 2>&1
          ./configure --prefix="$INSTALL_PREFIX" > /dev/null 2>&1
          make -j"$(nproc)" > /dev/null 2>&1
          make install > /dev/null 2>&1

          mv "$INSTALL_PREFIX/bin/valgrind" "$INSTALL_PREFIX/bin/valgrind_varlat"
          chmod -R u+rwX "$INSTALL_PREFIX"
          export PATH="$INSTALL_PREFIX/bin:$PATH"
          echo "PATH: $PATH"
          command -v valgrind_varlat
          echo "$INSTALL_PREFIX/bin" >> "$GITHUB_PATH"

      - name: Run valgrind_varlat tests
        shell: bash
        run: |
          set -eu -o pipefail
          cd "$GITHUB_WORKSPACE/tests/ct_tooling"
          chmod +x ct_test.sh
          raw_algs="${{ needs.interactive-inputs.outputs.runtime-options }}"
          IFS=',' read -r -a algs <<< "$raw_algs"    # convert to array
          for alg in "${algs[@]}"; do
            ./ct_test.sh valgrind-varlat ${{ matrix.compiler }} ${{ matrix.liboqs_build }} ${{ matrix.opt_flag }} "$alg"
          done

      - name: Upload valgrind_varlat logs
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
        with:
          name: valgrind_varlat_${{ matrix.compiler }}_${{ matrix.liboqs_build }}_${{ matrix.opt_flag }}_logs
          path: |
            tests/ct_tooling/tools/valgrind_varlat/logs/**

  memsan:
    needs: [interactive-inputs]
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    strategy:
      matrix:
        compiler: [clang]
        liboqs_build: [generic, auto]
        opt_flag: [-O1, -O2, -O3, -Os, -Ofast, "-O2 -fno-vectorize", "-O3 -fno-vectorize"]
      max-parallel: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Run memsan tests
        shell: bash
        run: |
          set -eu -o pipefail
          cd "$GITHUB_WORKSPACE/tests/ct_tooling"
          chmod +x ct_test.sh
          raw_algs="${{ needs.interactive-inputs.outputs.runtime-options }}"
          IFS=',' read -r -a algs <<< "$raw_algs"    # convert to array
          for alg in "${algs[@]}"; do
            ./ct_test.sh memsan ${{ matrix.compiler }} ${{ matrix.liboqs_build }} ${{ matrix.opt_flag }} "$alg"
          done

      - name: Upload memsan logs
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
        with:
          name: memsan_${{ matrix.compiler }}_${{matrix.liboqs_build}}_${{ matrix.opt_flag }}_logs
          path: |
            tests/ct_tooling/tools/memsan/logs/**