name: MacOS tests

permissions:
  contents: read

on: [workflow_call, workflow_dispatch]

jobs:

  macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
        CMAKE_ARGS:
          - -DOQS_ENABLE_SIG_SLH_DSA=OFF -DOQS_HAZARDOUS_EXPERIMENTAL_ENABLE_SIG_STFL_KEY_SIG_GEN=ON -DOQS_ENABLE_SIG_STFL_XMSS=ON -DOQS_ENABLE_SIG_STFL_LMS=ON
          - -DCMAKE_C_COMPILER=gcc-14
          - -DOQS_USE_OPENSSL=OFF
          - -DBUILD_SHARED_LIBS=ON -DOQS_DIST_BUILD=OFF
        exclude:
          # Failing configuration on Github actions; see https://github.com/open-quantum-safe/liboqs/pull/2148
          - os: macos-15
            CMAKE_ARGS: -DCMAKE_C_COMPILER=gcc-14

    runs-on: ${{ matrix.os }}
    timeout-minutes: 85 # max + 3*std over the last thousands of successful runs
    steps:
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # pin@v5
        with:
          python-version: '3.12'
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v4
      - name: Install dependencies
        run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja && pip3 install --require-hashes --break-system-packages -r .github/workflows/requirements.txt
      - name: Get system information
        run: sysctl -a | grep machdep.cpu
      - name: Configure
        run: mkdir -p build && cd build && source ~/.bashrc && cmake -GNinja -DOQS_STRICT_WARNINGS=ON ${{ matrix.CMAKE_ARGS }} .. && cmake -LA -N ..
      - name: Build
        run: ninja
        working-directory: build
      - name: Run tests
        env:
          OQS_TEST_SIG_CTX_STEP: "255"
        run: mkdir -p tmp && python3 -m pytest --verbose --ignore=tests/test_code_conventions.py --ignore=tests/test_kat_all.py --ignore=tests/test_acvp_vectors.py --ignore=tests/test_wycheproof_vectors.py
        timeout-minutes: 60
