name: Markdown Lint

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin@v4
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: |
          cp .github/workflows/package.json . && \
          cp .github/workflows/package-lock.json . && \
          npm install -g && \
          rm package.json && \
          rm package-lock.json && \

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules
