name: Release tests

on: # TODO: do we want to run this on pull request only? push only? need to have standardized release process
  push:
    branches: [ 'dev-**' ] # TODO: settle on prefix / suffix for release candidates
  pull_request:
    branches: [ 'dev-**' ]


jobs:

  oqs-provider-release-test:
    container:
      image: openquantumsafe/ci-ubuntu-jammy:latest # TODO: use this or the focal container?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oqs-provider
        uses: actions/checkout@v2
        with:
          repository: open-quantum-safe/oqs-provider
      - name: Checkout liboqs
        uses: actions/checkout@v2
        with:
          path: liboqs
      - name: Display everything
        run: pwd && ls

