name: Release tests

on:
  push:
    branches: [ 'sw-provider-**' ]
  pull_request:
    branches: [ 'dev-**' ]


jobs:

  oqs-provider-release-test: # TODO: this is highly coupled to oqs-provider structure. Might be better downstream?
    container:
      image: openquantumsafe/ci-ubuntu-jammy:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oqs-provider
        uses: actions/checkout@v4
        with:
          repository: open-quantum-safe/oqs-provider
      - name: Checkout liboqs
        uses: actions/checkout@v4
        with:
          path: liboqs
      - name: Activate all algorithms
        env:
          LIBOQS_SRC_DIR: liboqs
        run: |
          sed -i "s/enable\: false/enable\: true/g" oqs-template/generate.yml && \
          python3 oqs-template/generate.py
      - name: Full build
        env:
          OPENSSL_BRANCH: master # TODO: verify that this is the correct branch
        run: scripts/fullbuild.sh
          #- name: Run oqs-provider tests
          #run: scripts/runtests.sh
      - name: Run a minimal set of TLS tests
        env:
          OPENSSL_MODULES: _build/lib
          OPENSSL_CONF: scripts/openssl-ca.cnf
        run: |
          python3 -m pytest --numprocesses=auto scripts/test_tls_full.py::test_sig_kem_pair[ecdsap256-kyber512] \
          scripts/test_tls_full.py::test_sig_kem_pair[ecdsap256-p256_kyber512] \
          scripts/test_tls_full.py::test_sig_kem_pair[dilithium2-kyber512] \
          scripts/test_tls_full.py::test_sig_kem_pair[dilithium2-p256_kyber512] \
          scripts/test_tls_full.py::test_sig_kem_pair[p256_dilithium2-kyber512] \
          scripts/test_tls_full.py::test_sig_kem_pair[p256_dilithium2-p256_kyber512]
