name: Release tests

on: # TODO: do we want to run this on pull request only? push only? need to have standardized release process
  push:
    branches: [ 'sw-provider-**' ] # TODO: settle on prefix / suffix for release candidates
  pull_request:
    branches: [ 'sw-provider-**' ]


jobs:

  oqs-provider-release-test: # TODO: this is highly coupled to oqs-provider structure. Might be better downstream?
    container:
      image: openquantumsafe/ci-ubuntu-jammy:latest # TODO: use this or the focal container?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oqs-provider
        uses: actions/checkout@v4
        with:
          repository: open-quantum-safe/oqs-provider
      - name: Checkout liboqs
        uses: actions/checkout@v4
        with:
          path: liboqs
      - name: Activate all algorithms
        env:
          LIBOQS_SRC_DIR: liboqs
        run: |
          sed -i "s/enable\: false/enable\: true/g" oqs-template/generate.yml && \
          python3 oqs-template/generate.py
      - name: Full build
        run: scripts/fullbuild.sh
      - name: Run oqs-provider tests
        run: scripts/runtests.sh
      - name: Run full TLS tests
        env:
          OPENSSL_MODULES: _build/lib
          OPENSSL_CONF: scripts/openssl-ca.cnf
        run: python3 -m pytest --numprocesses=auto scripts/test_tls_full.py
