name: Release tests

on:
  release:
    types: [published]

jobs:
  # trigger oqs-provider release tests on a tracker branch
  oqs-provider-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger oqs-provider release tests
        run: |
          curl --silent \
               --write-out "\n%{response_code}\n" \
               --request POST \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.OQSBOT_GITHUB_ACTIONS }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               --data '{
                         "event_type": "liboqs-release",
                         "client_payload": {
                                             "liboqs_ref": "${{ github.event.release.tag_name }}",
                                             "provider_ref": "${{ github.event.release.tag_name }}-tracker"
                         }
                       }' \
               https://api.github.com/repos/open-quantum-safe/oqs-provider/dispatches | tee curl_out \
            && grep -q "204" curl_out
