name: Automatically label stale issues and pull requests

permissions:
  contents: read

on:
  schedule:
    # 5 am UTC everyday ~= 1 am or midnight America/Toronto
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      staleIssueDelay:
        description: "Days before an inactive issue is labeled stale"
        type: number
        required: true
        default: 180
      stalePullDelay:
        description: "Days before an inactive pull request is labeled stale"
        type: number
        required: true
        default: 30

jobs:
  label-inactive-issues-pr:
    name: Label inactive issues and pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    env:
      STALE_ISSUE_DELAY: ${{ inputs.staleIssueDelay || 180 }}
      STALE_PULL_DELAY: ${{ inputs.stalePullDelay || 30 }}
    steps:
      - name: Validate inputs
        if: ${{ env.STALE_ISSUE_DELAY <= 0 || env.STALE_PULL_DELAY <= 0 }}
        run: >
          echo "Invalid input: staleIssueDelay = ${{ env.STALE_ISSUE_DELAY }},
          stalePullDelay = ${{ env.STALE_PULL_DELAY}}"
      - name: Label inactive issues and pull requests
        uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # pin@v11
        with:
          days-before-issue-stale: ${{ env.STALE_ISSUE_DELAY }}
          days-before-issue-close: -1  # Do not automatically close issue or pull request
          stale-issue-label: "stale"
          stale-issue-message: >
            This issue has been inactive for ${{ env.STALE_ISSUE_DELAY }} days
            and flagged for maintainer review. It will not be automatically
            closed.
          days-before-pr-stale: ${{ env.STALE_PULL_DELAY }}
          stale-pr-label: "stale"
          stale-pr-message: >
            This pull request has been inactive for ${{ env.STALE_PULL_DELAY }}
            days and flagged for maintainer review. It will not be
            automatically closed.
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
